### ISSUE TITLE
incorrect promises implementation

### ISSUE THREAD

**Issue by dcharbonnier** [Level/levelup#741] opened 2022-03-23 11:03 UTC
`await db.open()` will never reject and an error event will be emitter crashing the process.

a dirty workaround that should not add issue the day this is fixed:
```
await new Promise<void>((resolve, reject) => {
        db.once("error", (err) => reject(err));
        db.open((err) => {
          if (err) {
            reject(err);
          } else {
            resolve();
          }
        });
      });
```

**Comment by vweevers** [comment] 2022-03-23 12:36
Duplicate of https://github.com/Level/levelup/issues/710

**Closed by vweevers** 2022-03-23 12:36 UTC

**Comment by dcharbonnier** [comment] 2022-03-23 13:04
#710 is closed, is this fix not released ?
