### ISSUE TITLE
createValueStream not containing all values

### ISSUE THREAD

**Issue by Rayzr522** [Level/levelup#418] opened 2017-02-21 14:39 UTC
I've been enjoying using LevelUP quite a bit, in fact I'm writing my own wrapper around it to provide a simpler interface. I wanted to create methods for `.keys()`, `.values()`, and `.entries()`. I was converting the streams to Promises, but I've encountered an odd problem. The output from `createValueStream()` only contains 3 of my 11 entries.

Output from `.values()`:
```javascript
[ false, true, { value: false } ]
```

Output from `.entries()`:
```javascript
[
    { key: 'bool-test-false', value: false },
    { key: 'bool-test-true', value: true },
    { key: 'not-exist', value: { value: false } },
    { key: 'null-test', value: null },
    { key: 'number-test-neg', value: -1 },
    { key: 'number-test-one', value: 1 },
    { key: 'number-test-zero', value: 0 },
    { key: 'object-test', value: { bool: true, str: 'Hello!', emptyStr: '', subObject: [Object] } },
    { key: 'object-test-empty', value: {} },
    { key: 'string-test', value: 'Hello' },
    { key: 'string-test-empty', value: '' }
]
```

`.keys()` and `.entries()` both return proper values, and I can work around this by getting the entries and filtering to only the values, but that's not as efficient. Just a note, `.createReadStream({ keys: false, values: true})` yields the same problem. Any ideas why this is happening?

**Comment by ralphtheninja** [comment] 2017-02-21 14:57
@Rayzr522 Any chance you can provide some code we can try out to see what's going on?

**Comment by Rayzr522** [comment] 2017-02-21 15:01
```javascript
db.unwrap().createValueStream()
    .on('data', value => {
        console.log(value);
    });
```
`db.unwrap()` just returns the actual LevelUP instance. 

Output:
```javascript
false
true
{ value: false }
```

**Comment by juliangruber** [comment] 2017-02-21 15:08
can you also give us the code that initializes the db and inserts the data?

**Comment by Rayzr522** [comment] 2017-02-21 15:10
At this point it would probably be better for you to see the code itself. [Here's my test class](https://github.com/Rayzr522/xpdb/blob/master/test/index.js), [the database wrapper](https://github.com/Rayzr522/xpdb/blob/master/lib/wrapper.js), [and the simple method that converts streams to promises](https://github.com/Rayzr522/xpdb/blob/master/lib/streams.js).

**Comment by juliangruber** [comment] 2017-02-21 15:24
it's a lot of work to look through that. you'll have better chances having this fixed by providing us with a simple complete gist to reproduce your problem.

**Comment by Rayzr522** [comment] 2017-02-21 15:30
Yeah, sorry about that. [Here you go](https://gist.github.com/Rayzr522/1f7f13180bcd93d606417bda23a814db).

**Comment by vweevers** [comment] 2017-02-21 15:43
Might be because you're inserting a value of `null` at [L20](https://gist.github.com/Rayzr522/1f7f13180bcd93d606417bda23a814db#file-levelup-value-stream-js-L20). Causing the underlying iterator to end early. The order of it makes sense too, as `key-10` comes after `key-1` lexicographically.

**Comment by Rayzr522** [comment] 2017-02-21 15:44
I commented that line out, but I still only got the 3 values. From before (`false`, `true`, and `'some value'`)

**Comment by juliangruber** [comment] 2017-02-21 15:49
which node version do i need to run this? or do i need to transform using babel?

**Comment by juliangruber** [comment] 2017-02-21 15:50
please also post how to run that file

**Comment by vweevers** [comment] 2017-02-21 15:50
@Rayzr522 I tried the same, got all values. Be sure to run it on an empty database, e.g.

```js
const db = level('./' + Date.now(), { valueEncoding: 'json' })
```

@juliangruber node 7 with `--harmony-async-await`

**Comment by Rayzr522** [comment] 2017-02-21 15:55
Ah, that worked now. Why do `null` values cause problems?

**Comment by juliangruber** [comment] 2017-02-21 15:55
i only get the first value. however, we're not waiting for any callback to fire in this example. that's expected behavior.

**Comment by vweevers** [comment] 2017-02-21 16:05
@juliangruber ah of course. Must have been luck when I ran it. So, ignoring promises and async/await for a moment:

```js
const level = require('level');
const db = level('./' + Date.now(), { valueEncoding: 'json' });

db.batch([
  { key: 'key-1', value: 1 },
  { key: 'key-2', value: 2 },
  { key: 'key-3', value: null },
  { key: 'key-4', value: 4 },
  { key: 'key-5', value: 5 }
], function (err) {
  if (err) throw err

  db.createValueStream()
    .on('data', (value) => {
      console.log(value)
    });
});
```

This stops at the null value.

**Comment by Rayzr522** [comment] 2017-02-21 16:13
But why?

**Comment by vweevers** [comment] 2017-02-21 16:39
Because of Node.js stream semantics, where null signifies EOF. 

@juliangruber isn't levelup supposed to throw if you try to insert `null` or `undefined`?

**Comment by Rayzr522** [comment] 2017-02-21 16:42
I'll add my own check for now, but you should definitely add an error for that. Thanks for your help!

**Comment by juliangruber** [comment] 2017-02-22 11:46
> Because of Node.js stream semantics, where null signifies EOF.
> 
> @juliangruber isn't levelup supposed to throw if you try to insert null or undefined?

Hm, dang. This might be the reason we had that in the first place and it might simply have been forgotten and thus we allow null now.

See https://github.com/nodejs/node/pull/6170 for discussion in node core, in the future you won't even be able to `stream.push(null)`. Streams suck ™️.

We're in a difficult spot here, because `null` is a valid JSON value..

```js
JSON.stringify(null)
// "null"
JSON.parse('null')
// null
```

..but object mode streams don't treat it as an acceptable value.

The options that I currently see are:

- use something that isn't node core streams, like es6 iterators or es6 streams
- define and implement our JSON encoding to be `"JSON without null"`

I think we should go with the second option. LevelUp can still accept null values, only the JSON encoding should throw on them.

What do other maintainers think?

**Comment by ralphtheninja** [comment] 2017-02-22 14:47
> We're in a difficult spot here, because null is a valid JSON value..

Aaaargh.

So hmm. Does this mean `createReadStream()` works as expected but `createValueStream()` doesn't?

**Comment by vweevers** [comment] 2017-02-22 15:37
> So hmm. Does this mean createReadStream() works as expected but createValueStream() doesn't?

Yea: that's `stream.push({ key, value: null })` vs `stream.push(null)`. With `createReadStream` there's no problem unless there's a downstream transformation. Some modules like `bytespace` do their own wrapping of `createReadStream`.

> LevelUp can still accept null values, only the JSON encoding should throw on them.

Are there any other (userland) encodings with the same problem? Perhaps the `id` encoding, though I can't think of a backend that can store `null` values. IndexedDB for example, can store almost any type *except* null IIRC.

**Closed** 2017-04-24 01:40 UTC
