### ISSUE TITLE
db.db.getProperty can't be used

### ISSUE THREAD

**Issue by zy445566** [Level/levelup#413] opened 2017-01-15 05:35 UTC
TypeError: this.db.db.getProperty is not a function.
I'm not find abstract-leveldown having this method!

**Comment by peakji** [comment] 2017-01-15 12:54
@zy445566 你好! I've tried levelup 1.3.3 with leveldown 1.5.3 on macOS and Windows, no problems here.
```javascript
const levelup = require("levelup");
const db = levelup("temp";)
console.log(db.db.getProperty("leveldb.sstables"));
```

**Comment by zy445566** [comment] 2017-01-16 02:22
@peakji Same as you write,but I can't.maybe I use cnpm (https://npm.taobao.org/).兄弟，其实我和你都是中国的，但为了其它人看懂，才用英文，你用的也是cnpm吗?我也是levelup 1.3.3和 leveldown 1.5.3，是在window10上操作的，不过我一开始用的是level直接弄，后来又按照你这弄，还是不行，都报db.db.getProperty is not a function,我这也是迷了，更迷的是approximateSize这个居然能用，看到它代码里的抽象那层和DeferredLevelDOWN这层确实没有。还是这个已经编译过来了，因为我看到leveldown官方说是纯C的

**Comment by peakji** [comment] 2017-01-16 03:36
@zy445566 Thanks for your feedback! I don't think it's related to node 7.3.0, all tests passed on Windows: [L767](https://ci.appveyor.com/project/Level/leveldown/build/job/38k3btwed2na5mcr). Could you run the  [getproperty-test](https://github.com/Level/leveldown/blob/master/test/getproperty-test.js) from leveldown and paste the results here?
--------------------------
你好，这应该不是 windows 和 node 7.3.0 的问题，我们的 CI 测试没有异常。请直接跑一下leveldown 里的 getproperty-test，然后反馈给我们吧，以确定问题是否在 leveldown 层面。

**Comment by zy445566** [comment] 2017-01-16 08:41
@peakji 
I can't believe that, at least I file is problem.
I find db.db is DeferredLevelDOWN,but not find "getProperty" method! 
https://github.com/Level/deferred-leveldown/blob/master/deferred-leveldown.js
https://github.com/Level/abstract-leveldown/blob/master/abstract-leveldown.js
Maybe you need send file to me.
我发现你所说的db.db是一个deferred-leveldown对象，而且继承于abstract-leveldow，而没有其它继承，却在这两个文件里面没有发现getProperty方法，你能把你能运行的库发给我看看吗？

**Comment by peakji** [comment] 2017-01-16 10:10
I've got it now, the error is caused by **deferred-leveldown**: `getProperty` is not deferrable at the moment.

@zy445566 please try the codes below:
```javascript
const levelup = require("levelup");

// TypeError: db.db.getProperty is not a function
function non_deferred() {
	var db = levelup("temp");
	console.log(db.db.getProperty("leveldb.sstables"));
}

// OK
function deferred() {
	var db = levelup("temp");
	setTimeout(function() {
		console.log(db.db.getProperty("leveldb.sstables"));
	}, 100);
}

deferred()
```

@juliangruber @ralphtheninja [getProperty](https://github.com/Level/leveldown/blob/master/leveldown.js#L61) is not required in **abstract-leveldown**, and is named differently (without the prefix underscore), so we cannot fix this issue by simply modifying [deferrables](https://github.com/Level/deferred-leveldown/blob/master/deferred-leveldown.js#L37). Do we need a special treat?

**Comment by juliangruber** [comment] 2017-01-16 10:11
so this is an issue with deferred-leveldown? if yes, let's open an issue there and then get it fixed

**Comment by peakji** [comment] 2017-01-16 10:41
@zy445566 A fast workaround: manually watch the status of your db instance and call `getProperty` once its fully opened.

I'm closing this issue now, for further discussion: https://github.com/Level/deferred-leveldown/issues/19

**Closed by peakji** 2017-01-16 10:41 UTC

**Comment by zy445566** [comment] 2017-01-16 10:58
Great!You find it!
const levelup = require("levelup");
const db = levelup("temp");
db.open(()=>{
	console.log(db.db);
	console.log(db.db.getProperty("leveldb.sstables"));
})
厉害了，这样是可以的
